@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class App {
  + App(): 
  + main(String[]): void
}
class ClientInit {
  + ClientInit(): 
  - playerId: String
  - color: String
  - firstPlayer: boolean
   playerId: String
   firstPlayer: boolean
   colour: String
   color: String
}
class ClientManager {
  ~ ClientManager(String): 
  + makeMove(int, List<Position>): MoveCommand
  + start(): ICommand
}
class ClientNew {
  + ClientNew(): 
  - firstPlayer: boolean
  - gameKind: String
  + pollingAgent: PollingAgent
  - playerId: String
  + sendMoveCommand(List<Position>): GameStatus
  + clientCallSync(ICommand): ICommand
  + sendGameKind(): void
  + clientCallAsync(ICommand): void
  + clientInit(): void
   playerId: String
   firstPlayer: boolean
   gameStatus: GameStatus
   pollingAgent: PollingAgent
   gameKind: String
}
class CoderDecoder {
  + CoderDecoder(): 
  ~ decodeCommand(String): ICommand
  ~ codeCommand(ICommand): String
  ~ decodeCall(String): String
  - decode(String, String): ICommand?
}
class CommandClass {
  + CommandClass(): 
  - type: String
  - value: String
   type: String
   value: String
}
class CommandFactory {
  + CommandFactory(): 
  + getClass(String): Class?
  + getCommand(String): ICommand?
}
class CzechKind {
  ~ CzechKind(): 
  - name: String
  - gameBoard: String[][]
  - capturedRequired: boolean
  - boardSize: int
  + isCapturePossible(int, String[][]): boolean
  + hasPieceUpgrade(int, Position): boolean
  + checkMoveKing(int, List<Position>, String[][]): Movement
  + checkMultiCaptureKing(int, List<Position>, String[][]): Movement
  + checkMultiCapturePiece(int, List<Position>, String[][]): Movement
  + checkMovePiece(int, List<Position>, String[][]): Movement
  + whoStarts(): int
   name: String
   boardSize: int
   gameBoard: String[][]
   capturedRequired: boolean
}
class GUIController {
  + GUIController(): 
  ~ player: ClientNew
  + lockBoard(): void
  ~ updateOnDemand(): void
  + getTurn(): void
  + movePiece(MouseEvent): void
  + showInstruction(ActionEvent): void
  + exitGame(ActionEvent): void
  + getTurnBasedOnGameStatus(GameStatus): void
  + unlockBoard(): void
   player: ClientNew
}
class GUIStart {
  + GUIStart(): 
  + start(Stage): void
}
class GUIbehaviour {
  ~ GUIbehaviour(): 
  - correctMove: boolean
  + addElement(Pane): void
  + removePiecesAfterMove(int, List<Position>, GridPane): void
  + transformIndexes(Node): Position
  + getImageName(String): String
  + updateBoard(String[][], GUIController): void
  + serverCheck(ClientNew, List<Pane>): List<Position>
  + deletePiece(Pane): void
  + getPositionFromPane(List<Pane>): List<Position>
  + copyFromTo(ArrayList<Pane>): void
  + add(Pane, String): void
   correctMove: boolean
}
class GameBoardManager {
  ~ GameBoardManager(GUIController, GameStatus): 
  + call(): Boolean
}
class GameKind {
  + GameKind(): 
  - kind: String
  - playerId: String
   playerId: String
   kind: String
}
class GameKindFactory {
  + GameKindFactory(): 
  + getGameKind(String): IGameKind
}
class GameManager {
  ~ GameManager(GameNew, Socket): 
  + run(): void
  - clientInitHandler(ClientInit, PrintWriter): void
  - moveCommandHandler(MoveCommand, PrintWriter): void
  - gameKindHandler(GameKind): void
  - gameStatusHandler(GameStatus, PrintWriter, Movement): void
}
class GameNew {
  ~ GameNew(): 
  - activePlayerID: String
  - player1ID: String
  - player2ID: String
  - numOfPlayers: int
  - board: String[][]
  - gameKind: IGameKind
  + addPlayer(): String
  + loadInitBoard(): void
  + move(List<Position>, String): Movement
   activePlayerID: String
   board: String[][]
   player1ID: String
   player2ID: String
   numOfPlayers: int
   gameKind: IGameKind
   gameKindName: String
}
class GameStatus {
  + GameStatus(): 
  ~ player2: String
  ~ gameKind: String
  ~ activePlayerID: String
  ~ capturedFigures: List<Position>
  ~ player1: String
  ~ board: String[][]
  ~ id: String
  ~ error: String
  ~ friendly_name: String
  ~ status: String
  ~ playerId: String
  + addCapturedFigure(Position): void
   activePlayerID: String
   playerId: String
   board: String[][]
   capturedFigures: List<Position>
   error: String
   status: String
   player1: String
   gameKind: String
   player2: String
   id: String
   friendly_name: String
}
class GermanKind {
  ~ GermanKind(): 
  - capturedRequired: boolean
  - boardSize: int
  - name: String
  - gameBoard: String[][]
  + whoStarts(): int
  + hasPieceUpgrade(int, Position): boolean
  + checkMoveKing(int, List<Position>, String[][]): Movement
  + checkMovePiece(int, List<Position>, String[][]): Movement
  + checkMultiCapturePiece(int, List<Position>, String[][]): Movement
  + isCapturePossible(int, String[][]): boolean
  + checkMultiCaptureKing(int, List<Position>, String[][]): Movement
   name: String
   boardSize: int
   gameBoard: String[][]
   capturedRequired: boolean
}
class GetCurrentGameStateClass {
  + GetCurrentGameStateClass(): 
  ~ id: String
  ~ playerId: String
   id: String
   playerId: String
}
interface ICommand << interface >>
interface IGameKind << interface >> {
  + whoStarts(): int
  + checkMultiCaptureKing(int, List<Position>, String[][]): Movement
  + checkMoveKing(int, List<Position>, String[][]): Movement
  + checkMovePiece(int, List<Position>, String[][]): Movement
  + checkMultiCapturePiece(int, List<Position>, String[][]): Movement
  + isCapturePossible(int, String[][]): boolean
  + hasPieceUpgrade(int, Position): boolean
   name: String
   boardSize: int
   gameBoard: String[][]
   capturedRequired: boolean
}
enum ImageType << enumeration >> {
  - ImageType(String): 
  + toString(): String
  + values(): ImageType[]
  + valueOf(String): ImageType
  + equalsName(String): boolean
}
class MoveCommand {
  ~ MoveCommand(): 
  ~ playerId: String
  ~ positions: List<Position>
  + clearPositions(): void
  + addPosition(Position): void
   positions: List<Position>
   playerId: String
}
class Movement {
  + Movement(): 
  - correctMove: boolean
  - errorMessage: String
  - kind: String
  - capturedFigures: List<Position>
  + addCapturedFigure(Position): void
  + isEqual(String, boolean, List<Position>, String): boolean
   kind: String
   capturedFigures: List<Position>
   correctMove: boolean
   errorMessage: String
}
class PollingAgent {
  ~ PollingAgent(ClientNew): 
  ~ gameStatus: GameStatus
  + stop(): void
  + run(): void
   gameStatus: GameStatus
}
class Position {
  + Position(): 
  - y: int
  - x: int
   y: int
   x: int
}
class Server {
  + Server(): 
  + main(String[]): void
}
class SwedishKind {
  ~ SwedishKind(): 
  - boardSize: int
  - name: String
  - gameBoard: String[][]
  - capturedRequired: boolean
  + checkMultiCapturePiece(int, List<Position>, String[][]): Movement
  + whoStarts(): int
  + hasPieceUpgrade(int, Position): boolean
  + checkMoveKing(int, List<Position>, String[][]): Movement
  + isCapturePossible(int, String[][]): boolean
  + checkMovePiece(int, List<Position>, String[][]): Movement
  + checkMultiCaptureKing(int, List<Position>, String[][]): Movement
   name: String
   boardSize: int
   gameBoard: String[][]
   capturedRequired: boolean
}
class TypesController {
  + TypesController(): 
  ~ player: ClientNew
  + choseType(ActionEvent): void
   player: ClientNew
}

ClientInit                -[#008200,dashed]-^  ICommand                 
ClientManager             -[#595959,dashed]->  CoderDecoder             : "«create»"
ClientManager            "1" *-[#595959,plain]-> "CD\n1" CoderDecoder             
ClientManager             -[#595959,dashed]->  MoveCommand              : "«create»"
ClientManager             -[#595959,dashed]->  Position                 : "«create»"
ClientNew                "1" *-[#595959,plain]-> "CD\n1" CoderDecoder             
ClientNew                 -[#595959,dashed]->  CoderDecoder             : "«create»"
ClientNew                "1" *-[#595959,plain]-> "commandFactory\n1" CommandFactory           
ClientNew                "1" *-[#595959,plain]-> "pollingAgent\n1" PollingAgent             
ClientNew                 -[#595959,dashed]->  PollingAgent             : "«create»"
CoderDecoder              -[#595959,dashed]->  CommandClass             : "«create»"
CommandFactory            -[#595959,dashed]->  ClientInit               : "«create»"
CommandFactory            -[#595959,dashed]->  GameKind                 : "«create»"
CommandFactory            -[#595959,dashed]->  GameStatus               : "«create»"
CommandFactory            -[#595959,dashed]->  GetCurrentGameStateClass : "«create»"
CommandFactory            -[#595959,dashed]->  MoveCommand              : "«create»"
CzechKind                 -[#008200,dashed]-^  IGameKind                
CzechKind                 -[#595959,dashed]->  Movement                 : "«create»"
CzechKind                 -[#595959,dashed]->  Position                 : "«create»"
GUIController            "1" *-[#595959,plain]-> "player\n1" ClientNew                
GUIController             -[#595959,dashed]->  GUIbehaviour             : "«create»"
GUIController             -[#595959,dashed]->  GameBoardManager         : "«create»"
GUIStart                  -[#595959,dashed]->  ClientNew                : "«create»"
GUIStart                  -[#595959,dashed]->  GameStatus               : "«create»"
GUIbehaviour              -[#595959,dashed]->  GameStatus               : "«create»"
GUIbehaviour             "1" *-[#595959,plain]-> "gameStatus\n1" GameStatus               
GUIbehaviour              -[#595959,dashed]->  Position                 : "«create»"
GameBoardManager          +-[#820000,plain]-  GUIController            
GameBoardManager         "1" *-[#595959,plain]-> "guiController\n1" GUIController            
GameBoardManager         "1" *-[#595959,plain]-> "initGameStatus\n1" GameStatus               
GameKind                  -[#008200,dashed]-^  ICommand                 
GameKindFactory           -[#595959,dashed]->  CzechKind                : "«create»"
GameKindFactory           -[#595959,dashed]->  GermanKind               : "«create»"
GameKindFactory           -[#595959,dashed]->  SwedishKind              : "«create»"
GameManager              "1" *-[#595959,plain]-> "CD\n1" CoderDecoder             
GameManager               -[#595959,dashed]->  CoderDecoder             : "«create»"
GameManager               -[#595959,dashed]->  GameKindFactory          : "«create»"
GameManager              "1" *-[#595959,plain]-> "gameKindFactory\n1" GameKindFactory          
GameManager              "1" *-[#595959,plain]-> "game\n1" GameNew                  
GameManager               -[#595959,dashed]->  GameStatus               : "«create»"
GameManager               -[#595959,dashed]->  Movement                 : "«create»"
GameNew                  "1" *-[#595959,plain]-> "gameKind\n1" IGameKind                
GameNew                   -[#595959,dashed]->  Movement                 : "«create»"
GameNew                   -[#595959,dashed]->  Position                 : "«create»"
GameStatus                -[#008200,dashed]-^  ICommand                 
GermanKind                -[#008200,dashed]-^  IGameKind                
GermanKind                -[#595959,dashed]->  Movement                 : "«create»"
GermanKind                -[#595959,dashed]->  Position                 : "«create»"
GetCurrentGameStateClass  -[#008200,dashed]-^  ICommand                 
MoveCommand               -[#008200,dashed]-^  ICommand                 
PollingAgent              +-[#820000,plain]-  ClientNew                
PollingAgent             "1" *-[#595959,plain]-> "client\n1" ClientNew                
PollingAgent             "1" *-[#595959,plain]-> "gameStatus\n1" GameStatus               
Server                    -[#595959,dashed]->  GameManager              : "«create»"
Server                    -[#595959,dashed]->  GameNew                  : "«create»"
SwedishKind               -[#008200,dashed]-^  IGameKind                
SwedishKind               -[#595959,dashed]->  Movement                 : "«create»"
SwedishKind               -[#595959,dashed]->  Position                 : "«create»"
TypesController          "1" *-[#595959,plain]-> "player\n1" ClientNew                
@enduml
